<footer id="site-footer" class="site-footer">
  <div class="top-footer">
    <div class="container">
      <div class="control">
        <ul>
          <li><a href="#modal-join">SUBSCRIBE TO EMAIL LIST</a></li>
          <li><a href="#">Contact Us</a></li>
        </ul>
      </div>
      <div class="social-links">
        <ul>
          <li class="social-1"><a href="#"></a></li>
          <li class="social-2"><a href="#"></a></li>
          <li class="social-3"><a href="#"></a></li>
          <li class="social-4"><a href="#"></a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="middle-footer">
      <span class="label">THANK YOU TO OUR PUBLIC PARTNERS</span>
      <ul>
        <li><a href="#"><img src="theme/images/tmp/partner-1-b.png" alt=""/></a></li>
        <li><a href="#"><img src="theme/images/tmp/partner-2-b.png" alt=""/></a></li>
        <li><a href="#"><img src="theme/images/tmp/partner-3-b.png" alt=""/></a></li>
        <li><a href="#"><img src="theme/images/tmp/partner-4-b.png" alt=""/></a></li>
      </ul>
    </div>
    <div class="bottom-footer">
      <div class="form form-search-footer">
        <input type="text" placeholder="SEARCH" autocomplete="off"/>
        <input type="submit" value="Submit" title="Search" class="form-submit"/>
      </div>
      <div class="info">
        <div class="logo"><a href="#"><img src="theme/images/logo-a.png" alt=""/></a></div>
        <address>
          111 NW 9th Street
          Oklahoma City, OK 73102
          405.605.7500
          <a href="mailto:oai@oaiquartz.org">oai@oaiquartz.org</a>
        </address>
        <p class="copy">Copyright 2016 © Oklahoma Arts Institute at Quartz Mountain</p>
      </div>
      <div class="navigation">
        <div class="menu-block-wrapper">
          <ul>
            <li>
              <a href="#">About</a>

              <div class="sublevel">
                <div class="col">
                  <h6>ABOUT</h6>
                  <ul>
                    <li><a href="#">What We Do</a></li>
                    <li><a href="#">History & Timeline</a></li>
                    <li><a href="#">Past Faculty Artists</a></li>
                  </ul>
                </div>
                <div class="col">
                  <h6>OUR PEOPLE</h6>
                  <ul>
                    <li><a href="#">Staff</a></li>
                    <li><a href="#">Board of Directors</a></li>
                    <li><a href="#">Artistic Advisory Panels</a></li>
                    <li><a href="#">Foundation Board</a></li>
                    <li><a href="#">Alumni</a></li>
                  </ul>
                </div>
              </div>
            </li>
            <li>
              <a href="#">Summer Arts Institute</a>

              <div class="sublevel">
                <div class="col">
                  <h6>ABOUT</h6>
                  <ul>
                    <li><a href="#">About OSAI</a></li>
                    <li><a href="#">Faculty</a></li>
                    <li><a href="#">Audition Schedule</a></li>
                    <li><a href="#">Application & Selection Process</a></li>
                    <li><a href="#">FAQs</a></li>
                    <li><a href="#">Participant Info</a></li>
                  </ul>
                </div>
                <div class="col">
                  <h6>DISCIPLINES</h6>
                  <ul>
                    <li><a href="#">Acting</a></li>
                    <li><a href="#">Ballet</a></li>
                    <li><a href="#">Chorus</a></li>
                    <li><a href="#">Creative Writing</a></li>
                    <li><a href="#">Drawing/Painting</a></li>
                    <li><a href="#">Film & Video</a></li>
                    <li><a href="#">Modern Dance</a></li>
                    <li><a href="#">Orchestra</a></li>
                    <li><a href="#">Photography</a></li>
                  </ul>
                </div>
              </div>
            </li>
            <li>
              <a href="#">Fall Arts Institute</a>

              <div class="sublevel">
                <div class="col">
                  <h6>ABOUT</h6>
                  <ul>
                    <li><a href="#">About OFAI</a></li>
                    <li><a href="#">Faculty</a></li>
                    <li><a href="#">Tuition & Enrollment</a></li>
                    <li><a href="#">K-12 Educators</a></li>
                    <li><a href="#">FAQs</a></li>
                    <li><a href="#">Participant Information</a></li>
                  </ul>
                </div>
                <div class="col">
                  <h6>WORKSHOPS</h6>
                  <ul>
                    <li><a href="#">Weekend One: October 6-9</a></li>
                    <li><a href="#">Weekend Two: October 13-16</a></li>
                    <li><a href="#">Weekend Three: October 20-23</a></li>
                  </ul>
                </div>
              </div>
            </li>
            <li>
              <a href="#">Quartz Mountain</a>

              <div class="sublevel">
                <div class="col">
                  <h6>QUARTZ MOUNTAIN</h6>
                  <ul>
                    <li><a href="#">About Quartz Mountain</a></li>
                    <li><a href="#">Facilities & Map</a></li>
                    <li><a href="#">Directions & Area Hotels</a></li>
                    <li><a href="#">Art Collection</a></li>
                  </ul>
                </div>
              </div>
            </li>
            <li>
              <a href="#">Support</a>

              <div class="sublevel">
                <div class="col">
                  <h6>SUPPORT OAI</h6>
                  <ul>
                    <li><a href="#">Donate Online</a></li>
                    <li><a href="#">Ways to Donate</a></li>
                    <li><a href="#">Our Donors</a></li>
                    <li><a href="#">OAI Foundation & Endowment Funds</a></li>
                    <li><a href="#">40th Anniversary Campaign</a></li>
                    <li><a href="#">Volunteer to be a Summer Counselor</a></li>
                  </ul>
                </div>
              </div>
            </li>
            <li>
              <a href="#">News & Events</a>

              <div class="sublevel">
                <div class="col">
                  <h6>WHAT’S NEW</h6>
                  <ul>
                    <li><a href="#">News & Community</a></li>
                    <li><a href="#">Events Calendar</a></li>
                    <li><a href="#">Tour de Quartz</a></li>
                  </ul>
                </div>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</footer>