<header id="site-header" class="site-header">
  <div class="container">
    <div class="logo"><a href="#"><img src="theme/images/logo.png" alt=""/></a></div>
    <div class="control">
     <div class="region region-top-header">
       <ul>
         <li><a href="#">OAI Shop</a></li>
         <li><a href="#">Donate Now</a></li>
         <li><a href="#">Contact Us</a></li>
       </ul>
     </div>
      <div class="search"><a href="#" class="top-search-button"></a>

        <form action="/" method="post" id="search-block-form--2" accept-charset="UTF-8"><div><div class="container-inline">
              <h2 class="element-invisible">Search form</h2>
              <div class="form-item form-type-textfield form-item-search-block-form">
                <label class="element-invisible" for="edit-search-block-form--4">Search </label>
                <input title="Enter the terms you wish to search for." placeholder="SEARCH" type="text" id="edit-search-block-form--4" name="search_block_form" value="" size="15" maxlength="128" class="form-text">
              </div>
              <div class="form-actions form-wrapper" id="edit-actions--3"><input type="submit" id="edit-submit--2" name="op" value="Search" class="form-submit"></div><input type="hidden" name="form_build_id" value="form-X6754tSvU5gzTogE9j9A5GfIUts3e6ktl1e4NSyEa4Q">
              <input type="hidden" name="form_id" value="search_block_form">
            </div>
          </div></form>
      </div>
    </div>
    <nav class="nav">
      <a class="btn-mobile" href="#"></a>
      <div class="menu-block-wrapper">
        <ul>
          <li>
            <a href="#">About</a>
            <div class="sublevel">
              <div class="col">
                <h6>ABOUT</h6>
                <ul>
                  <li><a href="#">What We Do</a></li>
                  <li><a href="#">History & Timeline</a></li>
                  <li><a href="#">Past Faculty Artists</a></li>
                </ul>
              </div>
              <div class="col">
                <h6>OUR PEOPLE</h6>
                <ul>
                  <li><a href="#">Staff</a></li>
                  <li><a href="#">Board of Directors</a></li>
                  <li><a href="#">Artistic Advisory Panels</a></li>
                  <li><a href="#">Foundation Board</a></li>
                  <li><a href="#">Alumni</a></li>
                </ul>
              </div>
            </div>
          </li>
          <li>
            <a href="#">Summer Arts Institute</a>
            <div class="sublevel">
              <div class="col">
                <h6>ABOUT</h6>
                <ul>
                  <li><a href="#">About OSAI</a></li>
                  <li><a href="#">Faculty</a></li>
                  <li><a href="#">Audition Schedule</a></li>
                  <li><a href="#">Application & Selection Process</a></li>
                  <li><a href="#">FAQs</a></li>
                  <li><a href="#">Participant Info</a></li>
                </ul>
              </div>
              <div class="col">
                <h6>DISCIPLINES</h6>
                <ul>
                  <li><a href="#">Acting</a></li>
                  <li><a href="#">Ballet</a></li>
                  <li><a href="#">Chorus</a></li>
                  <li><a href="#">Creative Writing</a></li>
                  <li><a href="#">Drawing/Painting</a></li>
                  <li><a href="#">Film & Video</a></li>
                  <li><a href="#">Modern Dance</a></li>
                  <li><a href="#">Orchestra</a></li>
                  <li><a href="#">Photography</a></li>
                </ul>
              </div>
            </div>
          </li>
          <li>
            <a href="#">Fall Arts Institute</a>
            <div class="sublevel">
              <div class="col">
                <h6>ABOUT</h6>
                <ul>
                  <li><a href="#">About OFAI</a></li>
                  <li><a href="#">Faculty</a></li>
                  <li><a href="#">Tuition & Enrollment</a></li>
                  <li><a href="#">K-12 Educators</a></li>
                  <li><a href="#">FAQs</a></li>
                  <li><a href="#">Participant Information</a></li>
                </ul>
              </div>
              <div class="col">
                <h6>WORKSHOPS</h6>
                <ul>
                  <li><a href="#">Weekend One: October 6-9</a></li>
                  <li><a href="#">Weekend Two: October 13-16</a></li>
                  <li><a href="#">Weekend Three: October 20-23</a></li>
                </ul>
              </div>
            </div>
          </li>
          <li>
            <a href="#">Quartz Mountain</a>
            <div class="sublevel">
              <div class="col">
                <h6>QUARTZ MOUNTAIN</h6>
                <ul>
                  <li><a href="#">About Quartz Mountain</a></li>
                  <li><a href="#">Facilities & Map</a></li>
                  <li><a href="#">Directions & Area Hotels</a></li>
                  <li><a href="#">Art Collection</a></li>
                </ul>
              </div>
            </div>
          </li>
          <li>
            <a href="#">Support</a>
            <div class="sublevel">
              <div class="col">
                <h6>SUPPORT OAI</h6>
                <ul>
                  <li><a href="#">Donate Online</a></li>
                  <li><a href="#">Ways to Donate</a></li>
                  <li><a href="#">Our Donors</a></li>
                  <li><a href="#">OAI Foundation & Endowment Funds</a></li>
                  <li><a href="#">40th Anniversary Campaign</a></li>
                  <li><a href="#">Volunteer to be a Summer Counselor</a></li>
                </ul>
              </div>
            </div>
          </li>
          <li>
            <a href="#">News & Events</a>
            <div class="sublevel">
              <div class="col">
                <h6>WHAT’S NEW</h6>
                <ul>
                  <li><a href="#">News & Community</a></li>
                  <li><a href="#">Events Calendar</a></li>
                  <li><a href="#">Tour de Quartz</a></li>
                </ul>
              </div>
            </div>
          </li>
        </ul>
      </div>
    </nav>
  </div>
</header>